// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqGnF1cMHlOg3pP62ZuIor9hyMjqznrY',
    appId: '1:986037500255:web:fd5ec502d5024337685eea',
    messagingSenderId: '986037500255',
    projectId: 'donotnote-d6d2b',
    authDomain: 'donotnote-d6d2b.firebaseapp.com',
    storageBucket: 'donotnote-d6d2b.appspot.com',
    measurementId: 'G-R2N14ET0XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvXHgYR4p4qCARJs5u23f9qKWh1Ob5ow',
    appId: '1:986037500255:android:5aef6b4782fdd0b5685eea',
    messagingSenderId: '986037500255',
    projectId: 'donotnote-d6d2b',
    storageBucket: 'donotnote-d6d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_OdYcJU6oOfvMfxJ7L1xS_OxFPXNCwJw',
    appId: '1:986037500255:ios:08016430ece6d095685eea',
    messagingSenderId: '986037500255',
    projectId: 'donotnote-d6d2b',
    storageBucket: 'donotnote-d6d2b.appspot.com',
    iosBundleId: 'com.three.donotnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_OdYcJU6oOfvMfxJ7L1xS_OxFPXNCwJw',
    appId: '1:986037500255:ios:2ab6852d2f6f0930685eea',
    messagingSenderId: '986037500255',
    projectId: 'donotnote-d6d2b',
    storageBucket: 'donotnote-d6d2b.appspot.com',
    iosBundleId: 'com.three.donotnote.RunnerTests',
  );
}
